name: Import Power Pages to Target Environment

on:
  push:
    branches:
      - main

jobs:
  export:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Install Power Platform CLI
      run: |
        Invoke-WebRequest -Uri https://aka.ms/PowerAppsCLI -OutFile pac.msi
        Start-Process msiexec.exe -ArgumentList '/i pac.msi /quiet /norestart' -NoNewWindow -Wait

    - name: Add pac to PATH
      shell: pwsh
      run: |
        $pac = (Get-Item "$env:POWERPLATFORMTOOLS_PACPATH").Directory.FullName;
        "$pac" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Log Current Directory
      run: |
        Write-Host "Current directory:"
        pwd

    - name: Log Directory Contents
      run: |
        Write-Host "Files in the current directory:"
        Get-ChildItem -Path . -Recurse  
    
    - name: Authenticate with Power Platform
      run: |
        pac auth create --name "OLDPORTAL" --url "https://orgbc24f670.crm.dynamics.com" --username "admin@CRM720692.onmicrosoft.com" --password "#W4^eG+p+u5L676wO="
    - name: Import Solution
      run: |
        pac paportal upload --path "exported_solution.zip/portalsitetest---site-p8dn9"


