name: Export Power Pages to GitHub
# Export solution from DEV environment
# Unpack, update version in Solution.xml and .nuspec file
# Pack and create branch
 
on: workflow_dispatch
 
jobs:
  export:
    runs-on: windows-latest
  
  Export-Branch:
    runs-on: powerapps
    env:
      RUNNER_DEBUG: 1
 
    steps:
 
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Install Power Platform CLI
      run: |
        Invoke-WebRequest -Uri https://aka.ms/PowerAppsCLI -OutFile pac.msi
        Start-Process msiexec.exe -ArgumentList '/i pac.msi /quiet /norestart' -NoNewWindow -Wait

    - name: Add pac to PATH
      shell: pwsh
      run: |
        $pac = (Get-Item "$env:POWERPLATFORMTOOLS_PACPATH").Directory.FullName;
        "$pac" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Authenticate with Power Platform
      run: |
        pac auth create --name "OLDPORTAL" --url "https://org9ef0d3ff.crm.dynamics.com" --applicationId ${{ secrets.CLIENT_ID }} --clientSecret ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
        

    - name: Export Solution
      run: |
        pac paportal download --path "exported_solution.zip" --webSiteId "5fea08ee-97cd-ef11-b8e8-6045bd06243c"

    - name: Verify Downloaded File
      run: |
        if (Test-Path -Path "exported_solution.zip") {
          Write-Host "File downloaded successfully: exported_solution.zip"
        } else {
          Write-Host "File not found: exported_solution.zip"
          exit 1
        }

    - name: Log Current Directory
      run: |
        Write-Host "Current directory:"
        pwd

    - name: Log Directory Contents
      run: |
        Write-Host "Files in the current directory:"
        Get-ChildItem -Path . -Recurse
 
    - name: Branch Solution
      id: BranchSolution
      uses: microsoft/powerplatform-actions/branch-solution@latest
      with:
        solution-folder: exported_solution.zip
        solution-target-folder: exported_solution.zip/
        branch-name: OLDPORTAL-CI
        repo-token: ${{ secrets.PAT_TOKEN }}
        allow-empty-commit: true
