name: Export Power Pages to GitHub

on:
  push:
    branches:
      - main

jobs:
  export:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Locate Power Platform CLI
      run: |
        $pacPath = Get-Command pac | Select-Object -ExpandProperty Path
        if ($pacPath) {
          $env:Path += ";" + [System.IO.Path]::GetDirectoryName($pacPath)
        } else {
          Write-Error "Power Platform CLI not found."
        }

    - name: Verify Power Platform CLI Installation
      run: |
        pac --version

    - name: Authenticate with Power Platform
      shell: pwsh
      run: |
        pac auth create --url https://org9ef0d3ff.crm.dynamics.com --client-id ${{ secrets.CLIENT_ID }} --client-secret ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}

    - name: Export Solution
      shell: pwsh
      run: |
        pac solution export --name "<solution-name>" --path "exported_solution.zip" --managed

    - name: Extract Solution Files
      shell: pwsh
      run: |
        Expand-Archive -Path exported_solution.zip -DestinationPath ./exported_solution -Force

    - name: Push to GitHub
      shell: pwsh
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./exported_solution
        git commit -m "Automated export of Power Pages solution"
        git push origin main
